"""initial schema

Revision ID: 11212fb944a1
Revises: 
Create Date: 2025-07-21 13:31:20.578097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11212fb944a1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('series',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_series_id'), 'series', ['id'], unique=False)
    op.create_index(op.f('ix_series_name'), 'series', ['name'], unique=True)
    op.create_table('shards',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('intent', sa.String(length=255), nullable=False),
    sa.Column('vessel_name', sa.String(length=255), nullable=True),
    sa.Column('vessel_status', sa.String(length=100), nullable=True),
    sa.Column('world_location_id', sa.String(length=36), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('splinter_info', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shards_id'), 'shards', ['id'], unique=False)
    op.create_index(op.f('ix_shards_intent'), 'shards', ['intent'], unique=False)
    op.create_index(op.f('ix_shards_name'), 'shards', ['name'], unique=True)
    op.create_index(op.f('ix_shards_vessel_status'), 'shards', ['vessel_status'], unique=False)
    op.create_index(op.f('ix_shards_world_location_id'), 'shards', ['world_location_id'], unique=False)
    op.create_table('worlds',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('system', sa.String(length=255), nullable=True),
    sa.Column('shard_id', sa.String(length=36), nullable=True),
    sa.Column('geography', sa.Text(), nullable=True),
    sa.Column('culture_notes', sa.Text(), nullable=True),
    sa.Column('technology_level', sa.String(length=100), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shard_id'], ['shards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_worlds_id'), 'worlds', ['id'], unique=False)
    op.create_index(op.f('ix_worlds_name'), 'worlds', ['name'], unique=True)
    op.create_index(op.f('ix_worlds_shard_id'), 'worlds', ['shard_id'], unique=False)
    op.create_index(op.f('ix_worlds_system'), 'worlds', ['system'], unique=False)
    op.create_index(op.f('ix_worlds_technology_level'), 'worlds', ['technology_level'], unique=False)
    op.create_table('books',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('isbn', sa.String(length=20), nullable=True),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('chronological_order', sa.Integer(), nullable=True),
    sa.Column('series_id', sa.String(length=36), nullable=True),
    sa.Column('world_id', sa.String(length=36), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('cosmere_significance', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('isbn')
    )
    op.create_index(op.f('ix_books_chronological_order'), 'books', ['chronological_order'], unique=False)
    op.create_index(op.f('ix_books_id'), 'books', ['id'], unique=False)
    op.create_index(op.f('ix_books_publication_date'), 'books', ['publication_date'], unique=False)
    op.create_index(op.f('ix_books_series_id'), 'books', ['series_id'], unique=False)
    op.create_index(op.f('ix_books_title'), 'books', ['title'], unique=False)
    op.create_index(op.f('ix_books_world_id'), 'books', ['world_id'], unique=False)
    op.create_table('magic_systems',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('power_source', sa.String(length=255), nullable=True),
    sa.Column('world_id', sa.String(length=36), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('mechanics', sa.Text(), nullable=True),
    sa.Column('limitations', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_magic_systems_id'), 'magic_systems', ['id'], unique=False)
    op.create_index(op.f('ix_magic_systems_name'), 'magic_systems', ['name'], unique=False)
    op.create_index(op.f('ix_magic_systems_type'), 'magic_systems', ['type'], unique=False)
    op.create_index(op.f('ix_magic_systems_world_id'), 'magic_systems', ['world_id'], unique=False)
    op.create_table('characters',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('aliases', sa.Text(), nullable=True),
    sa.Column('species', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('world_of_origin_id', sa.String(length=36), nullable=False),
    sa.Column('first_appearance_book_id', sa.String(length=36), nullable=True),
    sa.Column('biography', sa.Text(), nullable=True),
    sa.Column('magic_abilities', sa.Text(), nullable=True),
    sa.Column('affiliations', sa.Text(), nullable=True),
    sa.Column('cosmere_significance', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['first_appearance_book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['world_of_origin_id'], ['worlds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_characters_first_appearance_book_id'), 'characters', ['first_appearance_book_id'], unique=False)
    op.create_index(op.f('ix_characters_id'), 'characters', ['id'], unique=False)
    op.create_index(op.f('ix_characters_name'), 'characters', ['name'], unique=False)
    op.create_index(op.f('ix_characters_species'), 'characters', ['species'], unique=False)
    op.create_index(op.f('ix_characters_status'), 'characters', ['status'], unique=False)
    op.create_index(op.f('ix_characters_world_of_origin_id'), 'characters', ['world_of_origin_id'], unique=False)
    op.create_table('book_characters',
    sa.Column('book_id', sa.String(length=36), nullable=False),
    sa.Column('character_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.PrimaryKeyConstraint('book_id', 'character_id')
    )
    op.create_table('character_relationships',
    sa.Column('character_id', sa.String(length=36), nullable=False),
    sa.Column('related_character_id', sa.String(length=36), nullable=False),
    sa.Column('book_context_id', sa.String(length=36), nullable=True),
    sa.Column('relationship_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_context_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['related_character_id'], ['characters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_character_relationships_book_context_id'), 'character_relationships', ['book_context_id'], unique=False)
    op.create_index(op.f('ix_character_relationships_character_id'), 'character_relationships', ['character_id'], unique=False)
    op.create_index(op.f('ix_character_relationships_id'), 'character_relationships', ['id'], unique=False)
    op.create_index(op.f('ix_character_relationships_related_character_id'), 'character_relationships', ['related_character_id'], unique=False)
    op.create_index(op.f('ix_character_relationships_relationship_type'), 'character_relationships', ['relationship_type'], unique=False)
    op.create_foreign_key(
        'fk_shards_world_location_id_worlds',
        'shards', 'worlds',
        ['world_location_id'], ['id']
    )
    op.create_foreign_key(
        'fk_worlds_shard_id_shards',
        'worlds', 'shards',
        ['shard_id'], ['id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_character_relationships_relationship_type'), table_name='character_relationships')
    op.drop_index(op.f('ix_character_relationships_related_character_id'), table_name='character_relationships')
    op.drop_index(op.f('ix_character_relationships_id'), table_name='character_relationships')
    op.drop_index(op.f('ix_character_relationships_character_id'), table_name='character_relationships')
    op.drop_index(op.f('ix_character_relationships_book_context_id'), table_name='character_relationships')
    op.drop_table('character_relationships')
    op.drop_table('book_characters')
    op.drop_index(op.f('ix_characters_world_of_origin_id'), table_name='characters')
    op.drop_index(op.f('ix_characters_status'), table_name='characters')
    op.drop_index(op.f('ix_characters_species'), table_name='characters')
    op.drop_index(op.f('ix_characters_name'), table_name='characters')
    op.drop_index(op.f('ix_characters_id'), table_name='characters')
    op.drop_index(op.f('ix_characters_first_appearance_book_id'), table_name='characters')
    op.drop_table('characters')
    op.drop_index(op.f('ix_magic_systems_world_id'), table_name='magic_systems')
    op.drop_index(op.f('ix_magic_systems_type'), table_name='magic_systems')
    op.drop_index(op.f('ix_magic_systems_name'), table_name='magic_systems')
    op.drop_index(op.f('ix_magic_systems_id'), table_name='magic_systems')
    op.drop_table('magic_systems')
    op.drop_index(op.f('ix_books_world_id'), table_name='books')
    op.drop_index(op.f('ix_books_title'), table_name='books')
    op.drop_index(op.f('ix_books_series_id'), table_name='books')
    op.drop_index(op.f('ix_books_publication_date'), table_name='books')
    op.drop_index(op.f('ix_books_id'), table_name='books')
    op.drop_index(op.f('ix_books_chronological_order'), table_name='books')
    op.drop_table('books')
    op.drop_index(op.f('ix_worlds_technology_level'), table_name='worlds')
    op.drop_index(op.f('ix_worlds_system'), table_name='worlds')
    op.drop_index(op.f('ix_worlds_shard_id'), table_name='worlds')
    op.drop_index(op.f('ix_worlds_name'), table_name='worlds')
    op.drop_index(op.f('ix_worlds_id'), table_name='worlds')
    op.drop_table('worlds')
    op.drop_index(op.f('ix_shards_world_location_id'), table_name='shards')
    op.drop_index(op.f('ix_shards_vessel_status'), table_name='shards')
    op.drop_index(op.f('ix_shards_name'), table_name='shards')
    op.drop_index(op.f('ix_shards_intent'), table_name='shards')
    op.drop_index(op.f('ix_shards_id'), table_name='shards')
    op.drop_table('shards')
    op.drop_index(op.f('ix_series_name'), table_name='series')
    op.drop_index(op.f('ix_series_id'), table_name='series')
    op.drop_table('series')
    # ### end Alembic commands ###
