"""Make world_id nullable in magic_systems

Revision ID: e80c350cea0b
Revises: 3c8fb0ba98da
Create Date: 2025-07-21 14:24:45.862621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e80c350cea0b'
down_revision: Union[str, Sequence[str], None] = '3c8fb0ba98da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('magic_systems', 'world_id', existing_type=sa.String(length=36), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
